categories_per_page: 5
min_length_category: 4
max_length_category: 50
publisher_per_page: 5
min_length_publisher: 4
max_length_publisher: 50
min_length_publisher_location: 4
max_length_publisher_location: 100
