categories_per_page: 5
min_length_category: 4
max_length_category: 50
publisher_per_page: 5
min_length_publisher: 4
max_length_publisher: 50
min_length_publisher_location: 4
max_length_publisher_location: 100
authors_per_page: 5
min_length_author: 4
max_length_author: 30
min_length_author_description: 4
max_length_author_description: 200
books_per_page: 5
min_length_book: 4
max_length_book: 100
min_length_book_description: 4
max_length_book_description: 255
min_length_book_edition: 4
max_length_book_edition: 255
min_book_pages: 10
users_per_page: 5
max_length_user: 50
max_length_user_email: 255
min_length_user_password: 6
categories:
  books_per_page: 8
books:
  related_book_limit: 4
